### ISSUE TITLE
启动时应用崩溃

### ISSUE THREAD

**Issue by ZhangZhenghao** [fython/PackageTracker#15]
我使用的是Google Play上的2.2版本~

```
08-22 07:06:04.640 23640-23640/info.papdt.express.helper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: info.papdt.express.helper, PID: 23640
                                                                           Theme: themes:{default=, iconPack:system}
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{info.papdt.express.helper/info.papdt.express.helper.ui.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList info.papdt.express.helper.dao.PackageDatabase.data' on a null object reference
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                            Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList info.papdt.express.helper.dao.PackageDatabase.data' on a null object reference
                                                                               at info.papdt.express.helper.dao.PackageDatabase.load(Unknown Source)
                                                                               at info.papdt.express.helper.dao.PackageDatabase.<init>(Unknown Source)
                                                                               at info.papdt.express.helper.dao.PackageDatabase.getInstance(Unknown Source)
                                                                               at info.papdt.express.helper.ui.MainActivity.onCreate(Unknown Source)
                                                                               at android.app.Activity.performCreate(Activity.java:6251)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

**Comment by fython** [comment]
了解
