### ISSUE TITLE
进设置闪退

### ISSUE THREAD

**Issue by runInFuture** [fython/PackageTracker#56]
进设置页闪退
手机型号 MX5，系统Android 5.1，堆栈如下
03-18 17:47:10.060 4361-4361/info.papdt.express.helper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: info.papdt.express.helper, PID: 4361
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{info.papdt.express.helper/info.papdt.express.helper.ui.SettingsActivity}: kotlin.TypeCastException: null cannot be cast to non-null type T
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2685)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2754)
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:187)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                             at android.os.Looper.loop(Looper.java:194)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5898)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
                                                                          Caused by: kotlin.TypeCastException: null cannot be cast to non-null type T
                                                                             at info.papdt.express.helper.ui.fragment.settings.AbsPrefFragment$PreferenceProperty.getValue(AbsPrefFragment.kt:57)
                                                                             at info.papdt.express.helper.ui.fragment.settings.SettingsMain.getMPrefDarkIcon(SettingsMain.kt)
                                                                             at info.papdt.express.helper.ui.fragment.settings.SettingsMain.onCreatePreferences(SettingsMain.kt:107)
                                                                             at moe.shizuku.preference.PreferenceFragment.onCreate(PreferenceFragment.java:227)
                                                                             at info.papdt.express.helper.ui.fragment.settings.AbsPrefFragment.onCreate(AbsPrefFragment.kt:25)
                                                                             at info.papdt.express.helper.ui.fragment.settings.SettingsMain.onCreate(SettingsMain.kt:73)
                                                                             at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                                                                             at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1187)
                                                                             at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1070)
                                                                             at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2374)
                                                                             at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                             at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
                                                                             at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
                                                                             at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
                                                                             at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1286)
                                                                             at android.app.Activity.performStart(Activity.java:6143)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2754) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:187) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                             at android.os.Looper.loop(Looper.java:194) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5898) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by fython** [comment]
感谢反馈，下一版本会进行修复。
