### ISSUE TITLE
使用快递 100 API 闪退

### ISSUE THREAD

**Issue by Love4Taylor** [fython/PackageTracker#58]
百度 API 则无法添加单号 (顺丰速运)

```
#######RuntimeEnvironmentInformation#######
crash time=2018-04-13 11:37:10.590
model=Pixel
android version=P(27)
brand=google
manufacturer=Google
board=sailfish
hardware=sailfish
device=sailfish
version name=3.1.0
supported_abis=arm64-v8a & armeabi-v7a & armeabi
display=PPP1.180208.014
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: info.papdt.express.helper, PID: 32229
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1018)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:985)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:935)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:896)
	at com.scwang.smartrefresh.layout.internal.pathview.PathsDrawable.createCachedBitmapIfNeeded(PathsDrawable.java:216)
	at com.scwang.smartrefresh.layout.internal.pathview.PathsDrawable.draw(PathsDrawable.java:128)
	at info.papdt.express.helper.view.DeliveryHeader.onDraw(DeliveryHeader.kt:141)
	at android.view.View.draw(View.java:19982)
	at android.view.View.updateDisplayListIfDirty(View.java:18857)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchDraw(SmartRefreshLayout.java:717)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.draw(View.java:19985)
	at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
	at android.view.View.updateDisplayListIfDirty(View.java:18857)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1234)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.draw(View.java:19985)
	at com.android.internal.policy.DecorView.draw(DecorView.java:784)
	at android.view.View.updateDisplayListIfDirty(View.java:18857)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:673)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:679)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:787)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3257)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3073)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2453)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1441)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7076)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:935)
	at android.view.Choreographer.doCallbacks(Choreographer.java:747)
	at android.view.Choreographer.doFrame(Choreographer.java:682)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:921)
	at android.os.Handler.handleCallback(Handler.java:819)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by fython** [comment]
在上一个正式版本应该已经修复了，先关闭 Issue。
