### ISSUE TITLE
升级 3.1.1 后设置以及第三个 tips 崩溃

### ISSUE THREAD

**Issue by Love4Taylor** [fython/PackageTracker#60]
```
#######RuntimeEnvironmentInformation#######
crash time=2018-05-05 16:36:48.681
model=Pixel
android version=P(27)
brand=google
manufacturer=Google
board=sailfish
hardware=sailfish
device=sailfish
version name=3.1.1
supported_abis=arm64-v8a & armeabi-v7a & armeabi
display=PPP1.180208.014
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: info.papdt.express.helper, PID: 21324
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:302)
	at moe.feng.kotlinyan.common.AndroidExtensionsKt.asInt(AndroidExtensions.kt:166)
	at moe.feng.kotlinyan.common.IntSharedPreferenceGetter.getValue(SharedPreferencesExtensions.kt:60)
	at info.papdt.express.helper.support.PTSettings.getPackageApiType(Unknown Source:10)
	at info.papdt.express.helper.ui.fragment.settings.SettingsMain.onCreatePreferences(SettingsMain.kt:116)
	at moe.shizuku.preference.PreferenceFragment.onCreate(PreferenceFragment.java:227)
	at info.papdt.express.helper.ui.fragment.settings.AbsPrefFragment.onCreate(AbsPrefFragment.kt:25)
	at info.papdt.express.helper.ui.fragment.settings.SettingsMain.onCreate(SettingsMain.kt:73)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1382)
	at android.app.Activity.performStart(Activity.java:7137)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2916)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:166)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:143)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:75)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

清除数据打开后 第三个 tips 时崩溃

```
#######RuntimeEnvironmentInformation#######
crash time=2018-05-05 16:39:19.440
model=Pixel
android version=P(27)
brand=google
manufacturer=Google
board=sailfish
hardware=sailfish
device=sailfish
version name=3.1.1
supported_abis=arm64-v8a & armeabi-v7a & armeabi
display=PPP1.180208.014
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: info.papdt.express.helper, PID: 22177
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1018)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:985)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:935)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:896)
	at com.scwang.smartrefresh.layout.internal.pathview.PathsDrawable.createCachedBitmapIfNeeded(PathsDrawable.java:216)
	at com.scwang.smartrefresh.layout.internal.pathview.PathsDrawable.draw(PathsDrawable.java:128)
	at info.papdt.express.helper.view.DeliveryHeader.onDraw(DeliveryHeader.kt:141)
	at android.view.View.draw(View.java:19982)
	at android.view.View.updateDisplayListIfDirty(View.java:18857)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchDraw(SmartRefreshLayout.java:717)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.draw(View.java:19985)
	at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
	at android.view.View.updateDisplayListIfDirty(View.java:18857)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:18848)
	at android.view.View.draw(View.java:19710)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
	at android.view.View.draw(View.java:19985)
	at com.android.internal.policy.DecorView.draw(DecorView.java:784)
	at android.view.View.updateDisplayListIfDirty(View.java:18857)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:673)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:679)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:787)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3257)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3073)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2453)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1441)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7076)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:935)
	at android.view.Choreographer.doCallbacks(Choreographer.java:747)
	at android.view.Choreographer.doFrame(Choreographer.java:682)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:921)
	at android.os.Handler.handleCallback(Handler.java:819)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by Love4Taylor** [comment]
设置可以通过卸载重装解决 tips 那部分只要出现就崩

**Comment by fython** [comment]
第一个问题现在修复了，一会就将更新提交到市场。

第二个问题似乎是使用的一个库的问题，暂未查明原因。

**Comment by hearsilent** [comment]
@fython Fixed https://github.com/fython/PackageTracker/pull/61
