### ISSUE TITLE
Android P DP4上刷新闪退

### ISSUE THREAD

**Issue by yiheng0** [fython/PackageTracker#64]
MIX2刷了来自Pixel的Android P DP4(treble) 之后刷新闪退
版本3.1.2
崩溃日志:
```
07-23 21:24:43.819  3267  3267 E AndroidRuntime: FATAL EXCEPTION: main
07-23 21:24:43.819  3267  3267 E AndroidRuntime: Process: info.papdt.express.helper, PID: 3267
07-23 21:24:43.819  3267  3267 E AndroidRuntime: java.lang.IllegalArgumentException: width and height must be > 0
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at com.scwang.smartrefresh.layout.internal.pathview.PathsDrawable.createCachedBitmapIfNeeded(PathsDrawable.java:216)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at com.scwang.smartrefresh.layout.internal.pathview.PathsDrawable.draw(PathsDrawable.java:128)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at info.papdt.express.helper.view.DeliveryHeader.onDraw(DeliveryHeader.kt:141)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:20207)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19082)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:19935)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchDraw(SmartRefreshLayout.java:717)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19073)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:19935)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:20210)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19082)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:19935)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19073)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:19935)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19073)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:19935)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19073)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:19935)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19073)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:19935)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19073)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:19935)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.draw(View.java:20210)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19082)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3312)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3116)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2485)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-23 21:24:43.819  3267  3267 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
很喜欢水表助手,希望能修复 (

**Comment by yiheng0** [comment]
经过测试,凡3.0以上均闪退,但2.7.1可以正常运行

**Comment by fython** [comment]
@yiheng0 最新版已修复。
