### ISSUE TITLE
快速切换bottom bar导致应用崩溃

### ISSUE THREAD

**Issue by charlestian** [fython/PackageTracker#7]
![Screenshot_20160730-114030.png](http://i.imgur.com/e3hFJa2.png)

**Comment by coderfox** [comment]
```
08-03 21:41:31.096    4113-4113/info.papdt.express.helper E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: info.papdt.express.helper, PID: 4113
    Theme: themes:{default=overlay:com.baranovgroup.nstyle, iconPack:com.baranovgroup.nstyle, com.android.systemui=overlay:com.baranovgroup.nstyle, com.android.systemui.navbar=overlay:com.baranovgroup.nstyle}
    java.lang.IllegalStateException: No activity
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1135)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
            at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1953)
            at android.app.Fragment.performActivityCreated(Fragment.java:2234)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:992)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
            at android.app.BackStackRecord.run(BackStackRecord.java:793)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
            at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5461)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
```
